"""Attach evidence-based interpretation without changing the sealed decision rule."""
from pathlib import Path
import json,shutil
import pandas as pd
ROOT=Path(__file__).resolve().parents[2];OUT=ROOT/'results/temporal_response_peft_20260919';E=Path(__file__).resolve().parent/'result_evidence'
def main():
    verification=json.loads((OUT/'VERIFICATION.json').read_text());assert verification['status']=='VERIFIED'
    raw=pd.read_csv(OUT/'RAW_SCORES.csv');response=pd.read_csv(E/'RESPONSE_DIAGNOSTIC_MEAN.csv');effects=pd.read_csv(OUT/'EFFECTS.csv')
    score=raw[raw.stage=='selected'].groupby(['panel','condition','arm']).nmae.mean().unstack()
    p='electricity_transfer';a=score.loc[(p,'SHIFT8')];d=response[(response.panel==p)&(response.stage=='selected')&(response.condition=='SHIFT8')].set_index('arm')
    point=lambda condition,base:100*(1-score.loc[(p,condition),'IDEAL']/score.loc[(p,condition),base])
    seeds=[]
    for seed,g in raw[(raw.panel==p)&(raw.stage=='selected')&(raw.condition=='SHIFT8')].groupby('seed'):
        z=g.set_index('arm').nmae;seeds.append((int(seed),float(100*(1-z.IDEAL/z.MAG_ONLY))))
    marker='\n<!-- FINAL_INTERPRETATION -->\n'
    extra=f'''## 실제로 확인된 구성요소의 역할

**TRP의 현재 방법론 근거는 확보하지 못했다.** 전력 전이 SHIFT8 nMAE는 TRP {a.TRP:.9f}, PLAIN {a.PLAIN:.9f}, B0 {a.B0:.9f}다. 일부 조건의 작은 이득이 있는 것과 핵심 직접 대조를 통과한 것은 다르다.

같은 조건의 B0 대비 절대 보정 nMAE는 TRP {d.loc['TRP','absolute_correction_nmae']:.9f}, PLAIN {d.loc['PLAIN','absolute_correction_nmae']:.9f}, IDEAL {d.loc['IDEAL','absolute_correction_nmae']:.9f}다. TRP의 B0 반응 왜곡은 {d.loc['TRP','response_distortion_from_B0']:.9f}로 작았다. 즉 반응을 유지하는 방향으로는 작동했지만, 이 고정 설정에서는 유용한 추가 적응도 거의 하지 않은 결과와 일치한다. 학습 불능·NaN·checkpoint 복원 실패가 원인은 아니다.

합성 SHIFT8의 이상적 반응 오차는 B0 {d.loc['B0','ideal_response_error']:.9f}, TRP {d.loc['TRP','ideal_response_error']:.9f}, PLAIN {d.loc['PLAIN','ideal_response_error']:.9f}, IDEAL {d.loc['IDEAL','ideal_response_error']:.9f}다. B0 반응 보존이 필요한 반응의 개선을 자동 의미하지 않는 사례다. λ=1의 이 실행에서 보인 함수 수준 결과이며, 모든 λ에서 필연적으로 실패한다는 증명이나 gradient 원인 기여율은 아니다. 보정량은 예측 MAE 개선율과 다른 지표다.

## IDEAL의 좁은 이득과 손해를 따로 남긴다

IDEAL은 전력 전이 SHIFT8에서 PLAIN 대비 {point('SHIFT8','PLAIN'):.4f}%, MAG_ONLY 대비 {point('SHIFT8','MAG_ONLY'):.4f}% 낮은 오차였다. 하지만 MAG 대비 seed별 이득은 {seeds[0][0]}에서 {seeds[0][1]:.4f}%, {seeds[1][0]}에서 {seeds[1][1]:.4f}%로 방향이 다르다. 같은 전력 전이에서 REFERENCE 이득은 {point('REFERENCE','MAG_ONLY'):.4f}%, FAULT 이득은 {point('FAULT','MAG_ONLY'):.4f}%로 둘 다 손해다.

이것은 이미 정해둔 단순 대조군의 사후 기술 통계다. 새로운 주 성공 기준이나 우승자로 바꾸지 않는다. 일부 오류 악화만으로 모든 가능성을 폐기한 것이 아니라, TRP 자체가 핵심 직접 대조에서 뒤졌고 IDEAL의 우위도 조건·seed에 제한된다는 구분이다. IDEAL과 기존 MAG의 수치는 새로운 다중비교 유의성 결론으로 제시하지 않는다.

## 방법론 논문 목표에 대한 현재 판단

구현·학습·평가·검산은 완료했지만, 목표였던 '새 방법의 추가 가치를 뒷받침하는 방법론 논문 근거'는 아직 충족하지 못했다. 이 결과를 기존 분석 논문의 다른 제목으로 대체하지 않는다. 반응 차이를 맞추는 일반 수식은 이미 선행에 있으므로 TRP라는 이름이나 L1 변경만으로 신규성을 주장할 수 없다. [선행 수식 검토](../../research/temporal_response_method_20260919/NOVELTY_AUDIT_KO.md).

독립 자료 확인, 더 많은 seed 및 정식 PEFT 비교가 남았다는 사실은 이번 불리한 결과를 뒤집는 증거가 아니다. 현재 고정 TRP를 자동 재튜닝하거나 IDEAL을 사후 새 제안법으로 이름만 바꾸지 않는다. 새 학습은 추가하지 않았다.

[효과 그림 PDF](../../research/temporal_response_method_20260919/result_evidence/effects.pdf), [seed·자원·학습 손실 추가 근거](../../research/temporal_response_method_20260919/result_evidence/EVIDENCE_REVIEW_KO.md), [저장 예측 반응 진단](../../research/temporal_response_method_20260919/result_evidence/RESPONSE_DIAGNOSTIC_KO.md), [학습 장부 독립 검산](TRAINING_AUDIT.json), [평가 전 재사용 검사 수정](AMENDMENT_01_KO.md).
'''
    for name in ['REPORT.md','FINAL_DECISION.md']:
        backup=OUT/name.replace('.md','_AUTOGENERATED.md')
        if not backup.exists():shutil.copy2(OUT/name,backup)
    s=(OUT/'REPORT.md').read_text().split(marker)[0];(OUT/'REPORT.md').write_text(s+marker+extra)
    s=(OUT/'FINAL_DECISION.md').read_text().split(marker)[0]
    s+=marker+'''## 전체 목표의 완료 상태

새 PEFT 방법의 추가 가치와 신규성을 확보하려는 전체 목표는 **미달**이다. 실행 완료를 목표 달성으로 표시하지 않는다. TRP는 현재 고정 설정에서 중단할 후보이며, IDEAL의 전력 SHIFT8 좁은 이득과 원자료·오류 손해·seed 방향 차이는 보존한다. 그 대조군을 자동으로 새 제안법으로 승격하거나 새 학습을 실행하지 않는다. 선행과의 차별성·독립 확인 없이 방법론 논문이 완성됐다고 쓰지 않는다.
'''
    (OUT/'FINAL_DECISION.md').write_text(s)
if __name__=='__main__':main()
