"""Post-run descriptive diagnosis from fixed scores. No fitting or threshold changes."""
import csv,json,math
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'results/building_transfer_subspace_v1_20260915'
def main():
    rows=list(csv.DictReader((OUT/'scores.csv').open()));local=json.loads((OUT/'local_selection.json').read_text())['selected']['arm'];warm=json.loads((OUT/'warm_selection.json').read_text())['selected']['arm'];rank=json.loads((OUT/'stage1_recipe.json').read_text())['rank']
    mapping={'F0':'F0','AFFINE':'AFFINE','LOCAL':local,'LOCAL_FIXED120':f'local_r{rank}_fixed120','POOLED':'POOLED','POOLED_AFFINE':'POOLED_AFFINE','WARM':warm}
    def mean(role,arm,key='scaled_RMSE',days=None):
        v=[float(r[key]) for r in rows if r['role']==role and r['arm']==arm and (days is None or int(r['days'])==days)];assert len(v)==(8 if role=='tune' else 16)//(2 if days else 1);return sum(v)/len(v)
    gain=lambda b,t:100*(b-t)/b
    table=[]
    for arm,ta in mapping.items():table.append(dict(arm=arm,tune_scaled_RMSE=mean('tune',ta),dev_scaled_RMSE=mean('dev',arm),tune_gain_vs_F0=gain(mean('tune','F0'),mean('tune',ta)),dev_gain_vs_F0=gain(mean('dev','F0'),mean('dev',arm))))
    for row in table:
        row['tune_rank']=1+sum(r['tune_scaled_RMSE']<row['tune_scaled_RMSE'] for r in table);row['dev_rank']=1+sum(r['dev_scaled_RMSE']<row['dev_scaled_RMSE'] for r in table)
    with (OUT/'selection_transfer.csv').open('w',newline='') as f:w=csv.DictWriter(f,fieldnames=list(table[0]),lineterminator='\n');w.writeheader();w.writerows(table)
    l=next(r for r in table if r['arm']=='LOCAL_FIXED120');pool=next(r for r in table if r['arm']=='POOLED');raw=gain(mean('dev','F0','raw_RMSE'),mean('dev','LOCAL_FIXED120','raw_RMSE'));h={d:gain(mean('dev','F0',days=d),mean('dev','LOCAL_FIXED120',days=d)) for d in [3,14]}
    source=json.loads((OUT/'source_pooled_selection.json').read_text());s0=source['curve'][0]['source_validation_macro'];sb=source['selected']['source_validation_macro'];sg=gain(s0,sb)
    rs=list(csv.DictReader((OUT/'rank_resource_comparison.csv').open()));rr={int(r['rank']):r for r in rs};param=gain(float(rr[8]['trainable_parameters']),float(rr[1]['trainable_parameters']));mem=gain(float(rr[8]['median_peak_allocated_bytes']),float(rr[1]['median_peak_allocated_bytes']));speed=gain(float(rr[8]['median_gradient_seconds_per_update']),float(rr[1]['median_gradient_seconds_per_update']))
    lines=['# 결과 해석: 개선이 없는가, 선택한 개선이 전달되지 않는가?','','57 fits·8,616 updates 종료 후의 **기술적 사후 분석**이다. 추가 학습이나 gate 변경은 없다. 새로운 배포 규칙을 이 dev 점수로 선택하지 않는다.','','## 확인된 사실','','| 동일 비교군 | tune 주지표 | dev 주지표 | tune 순위 | dev 순위 | tune F0 대비 % | dev F0 대비 % |','| --- | ---: | ---: | ---: | ---: | ---: | ---: |']
    for r in table:lines.append(f"| {r['arm']} | {r['tune_scaled_RMSE']:.6f} | {r['dev_scaled_RMSE']:.6f} | {r['tune_rank']} | {r['dev_rank']} | {r['tune_gain_vs_F0']:+.3f} | {r['dev_gain_vs_F0']:+.3f} |")
    lines+=['',f"**표준 PEFT의 이득은 존재한다.** Rank1·fixed120은 dev 주지표 {l['dev_gain_vs_F0']:+.3f}%지만 tune에서는 {l['tune_gain_vs_F0']:+.3f}%다. 실제 선택된 짧은 학습보다 dev에서 좋았으므로 ‘업데이트를 줄이면 일반화 문제가 해결된다’고 결론 낼 수 없다. 반대로 dev를 보고 fixed120을 새 우승 recipe로 채택해 독립 성공이라고 부를 수도 없다.",'',f"**그 이득은 짧은 이력 전체의 성공도 아니다.** Fixed120의 F0 대비 개선은 H3 {h[3]:+.3f}%, H14 {h[14]:+.3f}%다. 더 짧은 H3에서는 악화했고 H14에서 개선했다. Raw RMSE 기준 개선은 {raw:+.3f}%라 주지표 개선과 방향도 다르다. 따라서 ‘8% 개선’은 history-scaled macro RMSE에 한정해서 읽어야 한다. H3/H14 scaling이 달라 두 H의 절대값을 직접 비교하지 않고, 각각 같은 H의 F0와 비교했다.",'',f"**공통 전이는 source 검증과 tune에서 좋아도 dev에서 뒤집혔다.** Source 미래 validation {sg:+.3f}%, tune F0 대비 {pool['tune_gain_vs_F0']:+.3f}%, dev F0 대비 {pool['dev_gain_vs_F0']:+.3f}%다. 데이터·건물마다 잔차의 크기와 방향이 달라 공통 low-rank 변화를 그대로 옮기는 가정이 부족하다는 해석과 일치한다. 다만 source 구성·달력·site·전처리·표본 크기 중 어떤 요인이 원인인지 분리한 인과 실험은 아니다.",'',f"**출력 보정이 공통 전이의 손해를 상당히 줄였다.** Dev POOLED→POOLED_AFFINE은 주지표 {gain(mean('dev','POOLED'),mean('dev','POOLED_AFFINE')):+.3f}% 개선이다. 이는 amplitude/offset 불일치가 일부 작용한다는 단서지만, 보정 후에도 최강 보고 대조군인 fixed120을 넘지 못했다. Source 정보와 두 출력 계수의 효과를 새로운 내부 PEFT 구조의 효과로 합치지 않는다.",'',f"**파라미터 절감과 GPU 이득도 다르다.** Rank8→1은 trainable 수 {param:.1f}% 감소지만 같은 tuning episode의 median peak allocation 감소는 {mem:.2f}%, update당 시간 감소는 {speed:+.2f}%였다. 이 단일 실행에서 속도 개선은 관측되지 않았으며 미세한 시간 차이는 잡음과 분리하지 않았다.",'','## 이 결과로 가능한 결정','','현재 추천한 ‘공통 전이가 충분히 성립한 뒤 소수 계수만 적응한다’는 경로는 전이 전제가 미충족이다. 그 전제를 통과시키려고 source 건물·학습률·판정 기준을 다시 고르지 않는다. 소수 계수 방식36 fits는 미실행이며 성능 실패로 기록하지 않는다. 공통 모델이 실패했다고 모든 mixture/메타학습 방식이 불가능하다는 뜻도 아니다.','','반복 실패를 설명할 때 지금 입증된 범위는 **설정 선택용 건물의 순위가 새 건물에서 유지되지 않았다는 것**이다. ‘PEFT 자체가 불가능’이나 ‘무조건 과적합이 원인’은 현재 결과보다 강한 주장이다. 앞으로 방법론 논문으로 삼으려면 이 건물 간 선택의 불안정성을 target 미래 없이 줄이는 실제 원리를 먼저 입증해야 한다. 단순 early stopping·rank 축소·source pooling·LoRA bank를 새 이름으로 묶는 것만으로 신규성이 생기지 않는다. 이번 데이터로 즉석의 H별 규칙이나 gate를 만들어 PASS 처리하지 않는다.','','이 실험만으로 성공 가능한 신규 PEFT 주제가 확보되었다고 말할 수 없다. [REPORT](REPORT.md)의 한계와 원점수를 남기고 종료한다. 이후 연구 방향의 검토와 별도 학습은 분리해야 한다.','']
    (OUT/'INTERPRETATION.md').write_text('\n'.join(lines))
    stats=dict(analysis_only=True,additional_fits=0,local_fixed120_gain_H3=h[3],local_fixed120_gain_H14=h[14],local_fixed120_gain_raw_RMSE=raw,local_fixed120_gain_primary=l['dev_gain_vs_F0'],source_validation_gain=sg,rank1_parameter_reduction_percent=param,rank1_peak_allocation_reduction_percent=mem,rank1_seconds_per_update_reduction_percent=speed)
    (OUT/'interpretation_metrics.json').write_text(json.dumps(stats,indent=2)+'\n');print(json.dumps(stats,indent=2))
if __name__=='__main__':main()
